Ладно, это странно, но окей.
vlfz/sonata-locales pull request #15
Opened 2021-06-06 19:46 UTC by megavirus2

:+1: :3

2021-06-06 20:42 UTC, Enslavedd commented
щито ето...

2021-06-07 07:39 UTC, vlfz approved these changes

2021-06-07 07:40 UTC, vlfz commented
Скоро будут реализована система установки своих языков для бота.

2021-06-08 12:25 UTC, bit0r1n commented
ор

2021-06-14 14:33 UTC, vlfz requested changes

2021-06-14 14:33 UTC, vlfz commented on locales/js.json
> -    "help.description": ">>> **WARN!** Optional argument is **`[]`**\n**WARN!** Required argument is **`<>`**\n\n**WARN!** For more help with commands **type `%shelp [command]`**",
акуда

2021-07-06 05:01 UTC, closed without merging