Мррр!
vlfz/sonata-locales pull request #18
Opened 2021-06-08 14:30 UTC by swdblurple

2021-06-10 14:43 UTC, vlfz requested changes

2021-06-10 14:43 UTC, vlfz commented on locales/ru_meow.json
> +
так нельзя делать

2021-06-12 12:01 UTC, swdblurple commented
аче я сделал только что

2021-06-14 14:31 UTC, vlfz approved these changes

2021-06-14 14:32 UTC, merged