[UA] Новый перевод на укр.
vlfz/sonata-locales pull request #19
Opened 2021-06-10 17:37 UTC by megavirus2

2021-06-12 09:48 UTC, Mrsasha45op requested changes

2021-06-12 09:48 UTC, Mrsasha45op commented on locales/ua.json
> +    "security-info.enabled": "Включено",
Увімкнено

2021-06-12 09:48 UTC, Mrsasha45op commented on locales/ua.json
> +    "security-info.disabled": "Виключено",
Вимкнено

2021-06-12 09:48 UTC, Mrsasha45op commented on locales/ua.json
> +    "warns.count_me": "Кількість ваших попереджень: **%s**\nСняти попереждения: **[sqdsh.top/bot_warn_appeal](https://sqdsh.top/bot_warn_appeal)** [на англійській]\n",
Зняти попереждения

2021-06-12 09:48 UTC, Mrsasha45op commented on locales/ua.json
> +    "about.description": "Привет! Мене звати **Соната**! Мене винайшов [%s](%s) за чашкою кави і восьмигодинною роботою за своїм робочим місцем.\n\n> **Що я вмію?**\nДосить хороше питання. Я поки ніч
1. Допоможіть з перекладом на іншу мову
2. Підтримайте розробку бота! Мене створює лише одна людина! Натисність сюди для переходу на сайт DonationAlerts.

2021-06-12 09:48 UTC, Mrsasha45op commented on locales/ua.json
> +    "about.words.support.translate": "Допомога з переводом",
перекладом

2021-06-12 09:48 UTC, Mrsasha45op commented on locales/ua.json
> +    "error.description.spamMode.banned": "На сервері **%s** включений режим захисту від спам-розсилки. Так як у вас **%s/%s попереджень**, я автоматично видала вам бан на цьому сервері.\nЯкщо ви вваж
увімкнено

2021-06-12 09:48 UTC, Mrsasha45op commented on locales/ua.json
> +    "error.description.spamMode.force_banned": "На сервере **%s** включений режим захисту від спам-розсилки. Ви додані в чорний список бота через `%s`, я автоматично видала Вам бан на цьому сервері.\
увімкнено

2021-06-12 09:48 UTC, Mrsasha45op commented on locales/ua.json
> +    "error.description.no_language": "Язик ботів може бути тільки **`%s`**!",
мова ботів

2021-06-12 09:48 UTC, Mrsasha45op commented on locales/ua.json
> +    "error.description.no_mode": "Режим работы може бути вказан тільки як **`on/off`**",
роботи

2021-06-12 09:48 UTC, Mrsasha45op commented on locales/ua.json
> +    "error.description.no_color": "Не вказан HEX-код, або ж HEX-код некоректний.\n\n> Можливо ви не поставили `#` на початку. \n> Ви можете вибрати колір на цьому сайті: **[`www.color-hex.com`](https
вказано

2021-06-12 09:48 UTC, Mrsasha45op commented on locales/ua.json
> +    "push.play.empty_queue": "ℹ️ Порожня чергу, виходжу з голосового каналу! Побачимося! >w<",
Черга порожня

2021-06-12 09:48 UTC, Mrsasha45op commented on locales/ua.json
> +    "error.poke.description.self_user" : "У тебе на обличчі прищик? У тебе на обличчі... крихта від печеньки? \nА,ти хочеш тицьнути себе? Добре, але вкажи не себе а кого то іншого >w<",
А, ти (пробел нужен)
не себе, а когось іншого

2021-06-12 09:48 UTC, Mrsasha45op commented on locales/ua.json
> +    "error.slap.description.no_user" : "Ви не вказали учасника. \nДраться - це не добре. Але будь ласка, будь ніжніше і покажи кого ти хочеш вдарити?",
Битись
Але, будь ласка, будь

2021-06-12 09:48 UTC, Mrsasha45op commented on locales/ua.json
> +    "error.slap.description.self_user" : "БУДЬ ЛАСКА НЕ РОБИ СОБІ БОЛЯЧЕ! Краще світ ти цим не зробиш, а лише заподієш мені шкода>~<",
мені шкоди

2021-06-12 09:48 UTC, Mrsasha45op commented on locales/ua.json
> +    "tickle.description": ">~< Це непріятненько ... до такої міри, що він(-а) сміється."
неприємненько

2021-06-12 09:48 UTC, Mrsasha45op commented on locales/ua.json
> +    "lick.description": "Ауучч.. Цу дуже миило~~",
це

2021-06-14 14:31 UTC, vlfz commented
@megavirus2 Прошу, эксперт выдал изменения, которые нужно выполнить

2021-06-20 16:32 UTC, Mrsasha45op requested changes

2021-06-20 16:32 UTC, Mrsasha45op commented on locales/ua.json
> +    "about.description": "Привет! Мене звати **Соната**! Мене винайшов [%s](%s) за чашкою кави і восьмигодинною роботою за своїм робочим місцем.\n\n> **Що я вмію?**\nДосить хороше питання. Я поки ніч
Привіт

2021-07-06 05:01 UTC, closed without merging