Music locales
vlfz/sonata-locales pull request #5
Opened 2021-04-07 17:08 UTC by neppedboy

2021-04-07 17:10 UTC, vlfz approved these changes

2021-04-07 17:10 UTC, vlfz commented
@Mrsasha45op если что не так - отредачь, пожалуйста

2021-04-08 04:57 UTC, Mrsasha45op requested changes

2021-04-08 04:57 UTC, Mrsasha45op commented on locales/en.json
> +    "help.prefix.args": "<new prefix should be large than 1 and less than 8 symbols>",
larger than

2021-04-08 04:59 UTC, Mrsasha45op requested changes

2021-04-08 04:59 UTC, Mrsasha45op commented on locales/en.json
> +    "help.how_to": "An example of command using",
usage

2021-04-08 22:10 UTC, Walkyst commented on locales/en.json
> +    "error.play.description.not_found": "Your music is not defined.",
`Requested track not found` скорее всего лучше будет тут смотреться

2021-04-09 11:50 UTC, Mrsasha45op approved these changes

2021-04-09 13:00 UTC, Mrsasha45op approved these changes

2021-04-10 06:56 UTC, merged